"use client";

import { useState } from "react";

const CLOUD = { backgroundImage: "linear-gradient(to bottom, rgba(255,255,255,0.72), rgba(255,255,255,0.96)), url('/naano/images/proof-cloud-atmosphere-v1.png')" };

function MethodCard({ badge, title, desc, cta, primary, children }: { badge: string; title: string; desc: string; cta: string; primary?: boolean; children: React.ReactNode }) {
  return (
    <div className="flex flex-col rounded-2xl border border-gray-200/80 bg-white p-5">
      <div className="mb-5 flex h-40 items-center justify-center rounded-xl bg-gradient-to-b from-[#eaf0fb] to-white">{children}</div>
      <p className="text-[13px] font-medium text-gray-500">{badge}</p>
      <h3 className="mt-1 text-lg font-bold text-gray-900">{title}</h3>
      <p className="mt-2 flex-1 text-[14px] leading-relaxed text-gray-500">{desc}</p>
      <button className={`mt-5 rounded-xl py-3 text-sm font-semibold ${primary ? "bg-[#2563EB] text-white hover:bg-[#1d4fd7]" : "border border-gray-200 text-gray-900 hover:bg-gray-50"}`}>{cta}</button>
    </div>
  );
}

const ANSWERS = [
  "Scaling procurement for high-growth SaaS teams",
  "Lead magnet — share a useful resource that drives qualified engagement",
  "€500–1,000 — first creator test",
  "Benchmark report: how your spending stacks up against peer SaaS companies",
  "Vendor consolidation: simplify from fragmented to unified procurement",
  "Procurement leaders posting about cost optimization and efficiency wins",
];
const ANGLES = [
  ["01", "Peer Benchmark Report", "Lead magnet — Benchmark report", "Offers a free benchmark comparing procurement spend against peer SaaS companies, giving leaders a data point they don't currently have."],
  ["02", "Vendor Consolidation Reality Check", "Retour d'XP / Post texte", "Explores the common pattern of procurement tool sprawl and why consolidation becomes necessary."],
  ["03", "Scaling Readiness Check", "Carrousel", "A diagnostic-style carousel helping procurement leaders self-assess whether their setup can handle growth."],
  ["04", "Efficiency Wins for Procurement Leaders", "Étude de cas", "A pattern-based post on common efficiency wins procurement teams unlock by consolidating vendor management."],
];
const DO = ["Frame the benchmark report as a genuinely useful peer comparison tool", "Mention vendor consolidation as the core value (fragmented → unified)", "Speak specifically to scaling SaaS companies, not procurement in general", "Include a clear, low-friction CTA (comment/DM to get the report)", "Keep the tone like advice from a peer, not a product pitch"];
const AVOID = ["Don't invent specific savings numbers or dollar figures not provided", "Don't claim case studies or client results that weren't shared", "Don't use generic procurement jargon like 'streamline synergies'", "Don't make it sound like a paid ad—no heavy CTAs like 'Buy now'", "Don't reference creators' personal experience with the product if they haven't used it"];

function Brief({ created, onCreate }: { created: boolean; onCreate: () => void }) {
  return (
    <div className="mx-auto max-w-3xl rounded-2xl border border-gray-200 bg-white p-6 text-left shadow-sm">
      <div className="flex items-center gap-2"><h2 className="text-lg font-bold text-gray-900">Procurement Scale Launch</h2><span className="rounded-full bg-blue-50 px-2 py-0.5 text-[11px] font-semibold text-[#2563EB]">Generated by AI</span><span className="rounded-full bg-gray-100 px-2 py-0.5 text-[11px] text-gray-500">v1 · Draft</span></div>
      <Section label="Product"><ul className="mt-1 space-y-1 text-[14px] text-gray-600">{["A procurement platform built for high-growth SaaS teams to consolidate fragmented vendor management.", "Benchmark report comparing spend against peer SaaS companies.", "Built specifically for scaling procurement needs."].map((t) => <li key={t}>✓ {t}</li>)}</ul></Section>
      <Section label="Target persona"><p className="mt-1 text-[14px] font-semibold text-gray-900">Procurement Lead / Head of Procurement · High-growth SaaS · Europe & North America</p><ul className="mt-2 space-y-1 text-[14px] text-gray-600"><li>✓ Pain: Vendor management is fragmented across too many disconnected tools</li><li>✓ Pain: No visibility into how spend compares to peers</li><li>✓ Trigger: The company is scaling fast; old processes can no longer keep up</li></ul></Section>
      <Section label="Tone"><p className="mt-1 text-[14px] text-gray-600">Direct, peer-to-peer, and pragmatic—like one procurement leader giving another a useful data point, not a vendor pitching a product.</p></Section>
      <Section label="Validated angles · 4">
        <div className="mt-2 space-y-3">{ANGLES.map(([n, t, tag, d]) => (<div key={n} className="rounded-xl border border-gray-100 p-3"><div className="flex items-center justify-between"><p className="text-[14px] font-semibold text-gray-900"><span className="text-gray-400">{n}</span> {t}</p><span className="rounded-full bg-blue-50 px-2 py-0.5 text-[11px] font-semibold text-[#2563EB]">{tag}</span></div><p className="mt-1 text-[13px] text-gray-500">{d}</p></div>))}</div>
      </Section>
      <Section label="Do and avoid">
        <div className="mt-2 grid gap-6 sm:grid-cols-2">
          <div><p className="font-semibold text-gray-900">Do</p><ul className="mt-2 space-y-1.5 text-[13px] text-gray-600">{DO.map((t) => <li key={t} className="text-emerald-700">✓ <span className="text-gray-600">{t}</span></li>)}</ul></div>
          <div><p className="font-semibold text-gray-900">Avoid</p><ul className="mt-2 space-y-1.5 text-[13px] text-gray-600">{AVOID.map((t) => <li key={t} className="text-red-500">✕ <span className="text-gray-600">{t}</span></li>)}</ul></div>
        </div>
      </Section>
      <div className="mt-6 flex flex-wrap gap-3">
        <button onClick={onCreate} className={`rounded-xl px-5 py-2.5 text-sm font-semibold text-white ${created ? "bg-emerald-500" : "bg-[#2563EB] hover:bg-[#1d4fd7]"}`}>{created ? "✓ Campaign created" : "Create campaign →"}</button>
        <button className="rounded-xl border border-gray-200 px-4 py-2.5 text-sm font-semibold text-gray-800">🔖 Save to drafts</button>
        <button className="rounded-xl border border-gray-200 px-4 py-2.5 text-sm font-semibold text-gray-800">💬 Adjust with AI</button>
      </div>
    </div>
  );
}
function Section({ label, children }: { label: string; children: React.ReactNode }) {
  return <div className="mt-5 border-t border-gray-100 pt-4"><p className="text-[11px] font-semibold uppercase tracking-wide text-gray-400">{label}</p>{children}</div>;
}

export function BrandCampaignNew() {
  const [mode, setMode] = useState<"choose" | "ai">("choose");
  const [phase, setPhase] = useState<"prompt" | "processing" | "brief">("prompt");
  const [created, setCreated] = useState(false);
  const [prompt, setPrompt] = useState("We want creators to post about our product launch on LinkedIn, focusing on tech and SaaS audiences. Looking for authentic posts. Budget around $2000, targeting creators with 5k-50k followers.");

  const submit = () => { setPhase("processing"); setTimeout(() => setPhase("brief"), 1800); };

  if (mode === "ai") {
    return (
      <div className="rounded-3xl bg-cover bg-center p-10" style={CLOUD}>
        <button onClick={() => { setMode("choose"); setPhase("prompt"); setCreated(false); }} className="mb-6 text-sm text-gray-500 hover:text-gray-800">‹ Back</button>

        {phase === "prompt" && (
          <div className="mx-auto max-w-3xl text-center">
            <h1 className="flex items-center justify-center gap-3 font-[family-name:var(--font-jakarta)] text-[40px] font-bold tracking-[-0.03em] text-gray-900">
              {/* eslint-disable-next-line @next/next/no-img-element */}
              <img src="/naano/app/logo.svg" alt="" className="h-9 w-9" />Generate your campaign in one click
            </h1>
            <div className="mx-auto mt-8 max-w-2xl rounded-2xl border border-gray-200 bg-white p-5 text-left shadow-sm">
              <textarea value={prompt} onChange={(e) => setPrompt(e.target.value)} rows={3} className="w-full resize-none text-[15px] leading-relaxed text-gray-700 outline-none" />
              <div className="mt-3 flex justify-end"><button onClick={submit} className="flex h-9 w-9 items-center justify-center rounded-full bg-[#2563EB] text-white hover:bg-[#1d4fd7]">↑</button></div>
            </div>
          </div>
        )}

        {phase === "processing" && (
          <div className="flex flex-col items-center justify-center py-24 text-center">
            {/* eslint-disable-next-line @next/next/no-img-element */}
            <img src="/naano/app/logo.svg" alt="" className="h-12 w-12 animate-pulse" />
            <p className="mt-4 font-[family-name:var(--font-jakarta)] text-2xl font-bold text-gray-900">Preparing your campaign</p>
          </div>
        )}

        {phase === "brief" && (
          <div>
            <div className="mx-auto mb-6 max-w-3xl">
              <p className="mb-3 text-[13px] text-gray-500">Nao asked a few questions — your answers:</p>
              <div className="flex flex-wrap gap-2">{ANSWERS.map((a) => <span key={a} className="rounded-full bg-white px-3 py-1.5 text-[13px] text-gray-700 shadow-sm ring-1 ring-gray-100">{a}</span>)}</div>
            </div>
            <Brief created={created} onCreate={() => setCreated(true)} />
            {created && (
              <div className="mx-auto mt-6 max-w-3xl rounded-2xl border border-gray-200 bg-white p-5 shadow-sm">
                <p className="text-[14px] text-gray-500">Brief approved ✓ — next step:</p>
                <div className="mt-2 flex items-center gap-3"><span className="flex h-9 w-9 items-center justify-center rounded-full bg-emerald-500 text-white">✓</span><div><p className="font-semibold text-gray-900">Procurement Scale Launch <span className="ml-1 rounded-full bg-emerald-50 px-2 py-0.5 text-[11px] font-semibold text-emerald-600">Active</span></p><p className="text-[13px] text-gray-500">Your campaign is live. Browse creators whenever you are ready.</p></div></div>
                <div className="mt-4 flex gap-3"><a href="#marketplace" className="rounded-xl bg-[#2563EB] px-5 py-2.5 text-sm font-semibold text-white hover:bg-[#1d4fd7]">Open marketplace →</a><button className="rounded-xl border border-gray-200 px-4 py-2.5 text-sm font-semibold text-gray-800">Edit the brief</button></div>
              </div>
            )}
          </div>
        )}
      </div>
    );
  }

  return (
    <div className="rounded-3xl bg-cover bg-center p-10" style={CLOUD}>
      <button onClick={() => { window.location.hash = "campaigns"; }} className="mb-6 text-sm text-gray-500 hover:text-gray-800">‹ Back</button>
      <div className="text-center">
        <h1 className="flex items-center justify-center gap-3 font-[family-name:var(--font-jakarta)] text-[40px] font-bold tracking-[-0.03em] text-gray-900">
          {/* eslint-disable-next-line @next/next/no-img-element */}
          <img src="/naano/app/logo.svg" alt="" className="h-9 w-9" />How do you want to launch your campaign?
        </h1>
        <p className="mt-3 text-[17px] text-gray-500">Choose your method. You can change everything before launch.</p>
      </div>
      <div className="mx-auto mt-10 grid max-w-5xl gap-5 md:grid-cols-3">
        <MethodCard badge="Today · 14:30 · 15 min" title="Launch free with the Naano team" desc="A campaign manager turns your selection into a ready-to-launch campaign. You validate, they handle the rest." cta="Book my onboarding →" primary><span className="flex h-16 w-16 items-center justify-center rounded-full bg-gray-200 text-2xl">🧑‍💼</span></MethodCard>
        <div onClick={() => setMode("ai")} className="cursor-pointer">
          <MethodCard badge="5 min" title="Create with AI" desc="AI asks the right questions and prepares a fully editable brief." cta="Create with AI">
            {/* eslint-disable-next-line @next/next/no-img-element */}
            <img src="/naano/app/logo.svg" alt="" className="h-12 w-12" />
          </MethodCard>
        </div>
        <MethodCard badge="1 min" title="Start from your link" desc="Paste an influence campaign you already ran: Naano reuses the brief and structure." cta="Start from my link"><span className="rounded-lg bg-white px-3 py-2 text-sm text-gray-500 shadow-sm">🔗 notion.site/brief…</span></MethodCard>
      </div>
    </div>
  );
}
